server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: wallet-service
  main:
    banner-mode: off

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.zalando.logbook: trace
